language: java

sudo: required

services:
  - docker

jdk:
- openjdk8

# safelist
branches:
  only:
  - master
  - release

before_install:
  - docker run -d -e SA_PASSWORD=5F4Dt9ky9dU$ -e SQLSERVER_DATABASE=sc -e SQLSERVER_USER=user -e SQLSERVER_PASSWORD=5F4Dt9ky9dU$ -p 1433:1433 exoplatform/sqlserver:2017-CU8
  - docker run -d -e POSTGRES_PASSWORD=5F4Dt9ky9dU$ -p 5432:5432 postgres:12.1
  - docker run -d -e MYSQL_ROOT_PASSWORD=5F4Dt9ky9dU$ -e MYSQL_DATABASE=sc -p 3306:3306 mysql:8.0.19

install:
  - sudo sed -i 's/us-central1.gce/us-central1.gce.clouds/' /etc/apt/sources.list
  - sudo apt-get update
  - wget --quiet http://www-us.apache.org/dist/lucene/solr/7.7.2/solr-7.7.2.tgz
  - tar -xf solr-7.7.2.tgz
  - ./solr-7.7.2/bin/solr start
  - ./solr-7.7.2/bin/solr create -c solr

script:
  - mvn -B -pl '!spring-eg-content-solr' -pl '!spring-eg-content-solr-boot-starter' deploy --settings settings.xml
  - mvn -B -pl spring-eg-content-solr -pl spring-eg-content-commons deploy --settings settings.xml
  - unset SOLR_PASSWORD
  - unset SOLR_USERNAME
  - export SOLR_URL=$INSECURE_SOLR
  - mvn -B -pl spring-eg-content-solr -pl spring-eg-content-commons deploy --settings settings.xml
  - unset SOLR_URL
  - mvn -B -pl spring-eg-content-solr-boot-starter deploy --settings settings.xml



